### ISSUE TITLE
Support for GCP Pub/Sub would be 🙌🏼

### ISSUE THREAD

**Issue by iToto** [batchcorp/plumber#1]

**Comment by dselans** [comment]
Hey there! I'd be happy to add GCP pub/sub support but I've never used it so I may need a bit of guidance on how you'd expect for it to work. I do have access to gcp, pub/sub and have the ability to create topics & subscriptions.

Would you expect to manually create a new subscription for `plumber` and then point the tool at that subscription? Can this be done programmatically? Can you shed some light on your use case? 

Thank you!

**Comment by iToto** [comment]
Hey @dselans yes I can definitely shed some light on the use case. So similar to your use cases with Kafka, it would be awesome to be able to use plumber to subscribe to a topic in PubSub and listen for events; It would be awesome to also be able to publish events.  

This would be super beneficial for testing and troubleshooting messages between services 🙌

**Comment by dselans** [comment]
👍  got it. I looked over the docs for it - looks very simple. I'll get it added soon.

**Comment by dselans** [comment]
Alright - released a new version with support for GCP PubSub: https://github.com/batchcorp/plumber/releases/tag/v0.0.3

Can you try it out - let me know if it works as you expect?

**Comment by iToto** [comment]
Yup, will have a look at it today with @hebime 🙌

**Comment by uzarubin** [comment]
@iToto Did you ever get a chance to test it out?

**Comment by iToto** [comment]
@uzarubin not yet good sir. Will try to test it out next week 👍🏼

**Comment by blinktag** [comment]
Closing as this is pretty old. If you have any trouble with plumber's GCP functionality, don't hesitate to file a new issue
