### ISSUE TITLE
Support for Azure Service Bus

### ISSUE THREAD

**Issue by K3UL** [batchcorp/plumber#12]
Hi,

Is there any plan to implement support for Azure Service Bus ?

**Comment by dselans** [comment]
Now that you've asked for it - will make it happen 😄 

"Build what people need" - that's basically the unofficial slogan for `plumber`!

I'll get this on the roadmap.

**Comment by K3UL** [comment]
How nice to hear !
My go is pretty rudimentary and I would not know where to start here, but I will keep my eye on it here and if I find time I can try to participate in this

**Comment by blinktag** [comment]
@K3UL Azure service bus has been added in [v0.11.0](https://github.com/batchcorp/plumber/releases/tag/v0.11.0)
It supports reading and writing to both queues and topics. Example usage can be found here: https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md

If you need any additional features, don't hesitate to open up a new issue!
