### ISSUE TITLE
Build from source error `github.com/batchcorp/schema`

### ISSUE THREAD

**Issue by Gsantomaggio** [batchcorp/plumber#137]
I am trying to build the project from source:

```shell
$ go mod vendor

go: github.com/batchcorp/schemas@v0.2.157: reading github.com/batchcorp/schemas/go.mod at revision v0.2.157: unknown revision v0.2.157
```

Actually, in the mod file the [schemas](https://github.com/batchcorp/plumber/blob/master/go.mod#L13) lib is required but the repository is [missing](http://github.com/batchcorp/schemas).

Am I missing something?

Thank you

**Comment by blinktag** [comment]
That repo is private unfortunately. I'll see if there is a workaround for this

**Comment by dselans** [comment]
Hi @Gsantomaggio - like @blinktag said, that repo is private, which is the reason the schemas are already vendored. Can you provide some insight as to what you're trying to do? Are you trying to add another external lib to the project?

Basically, it looks like we need to make the compiled schemas available publicly but that'll take a little elbow grease to get going. I'd like to see if maybe there's something else, in the meantime, we can do to unblock you.

**Comment by Gsantomaggio** [comment]
HI @dselans ,
Nothing special, I'd like to update the rabbitmq-go-stream client to the last version and propose a change for  [read](https://github.com/batchcorp/plumber/blob/master/backends/rabbitmq-streams/read.go#L56) behaviour.

with `-f` parameter works very well, without `-f` it just reads the first record then stop reading. 
maybe read `X` records and then stop or something like that. What do you think? 
Thank you

**Comment by dselans** [comment]
@Gsantomaggio got it - sounds good. We'll go ahead and split up our schemas so that the service defs are public (and keep our internal stuff private). We should have that stuff done really soon - will update here once it's good to go. Sorry about the hassle!

Re: single reads - maybe a `-c` to indicate count of how many messages you should read? `plumber` could output something like `Read '1' message (change with -c)`.

**Comment by Gsantomaggio** [comment]
>We should have that stuff done really soon - will update here once it's good to go. Sorry about the hassle!

Thank you, and no rush :)!

**Comment by blinktag** [comment]
@Gsantomaggio pull the latest changes and you'll be good to go

**Comment by Gsantomaggio** [comment]
it works! ty!
