### ISSUE TITLE
Support for Pulsar

### ISSUE THREAD

**Issue by uzarubin** [batchcorp/plumber#14]
Investigate support for https://pulsar.apache.org/docs/en/pulsar-2.0/

**Comment by blinktag** [comment]
Holding off on this until the official library has been moved from cgo

**Comment by mihaitodor** [comment]
This one is CGo free: https://github.com/apache/pulsar-client-go and the CGo one has been deprecated.

**Comment by blinktag** [comment]
@mihaitodor this has been released in [v0.24.0](https://github.com/batchcorp/plumber/releases/tag/v0.24.0)

Let us know if you need any additional functionality Pulsar functionality

**Comment by mihaitodor** [comment]
@blinktag Thank you very much! Will do :)
