### ISSUE TITLE
Support of KubeMQ Backend

### ISSUE THREAD

**Issue by kubemq** [batchcorp/plumber#142]
Hi Guys,
Some of our users asked us for integration with your platform.
Thanks for your great architecture, it was very easy and we have a ready PR to merge.
The KubeMQ backend support read, write, dynamic and relay. The only missing piece is the support of PB and the gRPC part that needs your attention and add the required schema.
Let me know what you need from us in order to complete the integration.

Lior,
KubeMQ CTO

**Comment by blinktag** [comment]
Fantastic, thank you Lior! If you can open a PR with what you have, I'll button up the rest. I'll need to make some changes to our internal services to handle the message relaying

**Comment by kubemq** [comment]
Thank you,
A PR was issued,
Let me know how i can help if needed.
Lior,

**Comment by blinktag** [comment]
Thank you for the PR Lior, KubeMQ support has been added in [v0.34](https://github.com/batchcorp/plumber/releases/tag/v0.34.0)
