### ISSUE TITLE
Can not use plumber to read message from nats-jetstream

### ISSUE THREAD

**Issue by edarha** [batchcorp/plumber#156]
Hi all, currently, I'm stuck on cannot read messages from nats-jetstream by plumber, Anyone can help me?

**Comment by dselans** [comment]
Hi @edarha - can you paste the command you are using to perform the read?

Also, what version of nats are you running?

**Comment by blinktag** [comment]
Hello @edarha 
What issue are you having with nats-streaming? 

We have some examples here if you need help getting started:
[Reading from nats streaming](https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md#nats-streaming)
[Publishing to nats streaming](https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md#nats-streaming-1)

These examples will work out of the box on the nats docker image in our [docker-compose.yml](https://github.com/batchcorp/plumber/blob/d8e3eabda6c395502ea5d99df1dcced3c3d2fd59/docker-compose.yml#L63)
Just spit it up using `docker compose up -d nats`

**Comment by tpihl** [comment]
nats streaming and nats jetstream is NOT the same thing. nats-streaming (aka stan) is depricated

info: 
https://docs.nats.io/nats-concepts/jetstream
https://docs.nats.io/legacy/stan

**Comment by blinktag** [comment]
@tpihl Thank you, don't know how I missed that!
Jetstream support has been added in https://github.com/batchcorp/plumber/releases/tag/v1.0.4

If you need any additional features, let us know!
