### ISSUE TITLE
Support for Avro

### ISSUE THREAD

**Issue by alok87** [batchcorp/plumber#17]
Support avro messages

**Comment by dselans** [comment]
Makes sense. 👍

**Comment by blinktag** [comment]
@alok87 I have added avro support in https://github.com/batchcorp/plumber/releases/tag/v0.6.0

You can use the `--avro-schema` flag to apply the schema when writing or reading:
```
$ plumber write kafka --topic=orders --avro-schema=some_schema.avsc --input-file=your_data.json
$ plumber read kafka --topic=orders --avro-schema=some_schema.avsc
```

Please let me know if this captures your use case correctly

**Comment by alok87** [comment]
Brilliant thanks!

**Comment by dselans** [comment]
Bad ass!
