### ISSUE TITLE
Listen to Kafka cluster messages

### ISSUE THREAD

**Issue by rasklaad** [batchcorp/plumber#18]
Hello, is there any way to listen messages from one of the instances from Kafka cluster?
I tried with 
```
./plumber-linux -d read message kafka --topic=my-topic-name --address=one.of.the.nodes:9092 
```
but I get message:
```
INFO[0000] Initializing (could take a minute or two) ...  pkg=kafka/read.go
```
Nothing happens even after 10 minutes

**Comment by dselans** [comment]
Hey there - the example you provided should work. Are you sure that your Kafka brokers accept non-ssl connections? See if your brokers are listening on `9094` and if so, use `--insecure-tls`.

**Comment by rasklaad** [comment]
I sure, that brokers listening on 9092: I can't read messages with the Java driver. I would like to provide more info to figure out what is happening, but seems like `-d` option doesn't help in this case. Is there another way to enable trace/info log?

**Comment by dselans** [comment]
@rasklaad I will see if there's a way to add a bit more debug output to help understand where we are in the "consuming process". With that said, can you describe your testing process?

In your case, I would do as follows:

1. Start one instance of `plumber` in "read" mode against your broker
2. Start another instance of `plumber` in "write" mode against your broker
3. See if the message shows up on the first instance of plumber.

If that doesn't work - I would update your Java code to consume from your broker and use `plumber` to write a dummy message. See if that works and go from there.

**Comment by Icedroid** [comment]
the same as the issuer. when I add --insecure-tls also get an error as follow:
```
plumber read message kafka --insecure-tls --address=one.of.the.nodes:9092 --topic=EVM_Billing_Test
FATA[0000] Unable to complete command: unable to create new reader: unable to create initial connection to host '125.88.39.158:31505': read tcp 10.8.2.170:63084->one.of.the.nodes:9092: read: connection reset by peer
```

**Comment by dselans** [comment]
@Icedroid are you able to write to that topic via `plumber`?

If you are certain that this is not a TLS issue, I think this might be a client/broker version problem.

Could you and @rasklaad let me know what versions your brokers are? Would be super helpful.

Thank you!

**Comment by dselans** [comment]
Closing this for now. Please provide version info :)

**Comment by rasklaad** [comment]
Sorry, I forgot about this issue.
I tried following:

1. Started one plumber in read mode
2. Push message from another instance of plumber
Still can't see message in read mode, but I can see pushed message by java driver

**Comment by alok87** [comment]
Facing the same issue. The cluster is hosted using [strimzi](https://strimzi.io
) in k8s.
