### ISSUE TITLE
Wrong value when sending JSON payload to Kafka

### ISSUE THREAD

**Issue by kamalhm** [batchcorp/plumber#19]
![image](https://user-images.githubusercontent.com/15316378/92212530-4eb57a80-eebc-11ea-8370-a58fe10da330.png)
Offset 14 is when I use kafka-console-producer, 

Offset 15 is using plumber with command `plumber write message kafka --topic test --input-data {"test":"with space"}`

**Comment by dselans** [comment]
@kamalhm is this not expected? Each write would bump the offset - is that not right?

**Comment by kamalhm** [comment]
The offset is expected, but take a look at the message received

**Comment by dselans** [comment]
Oh jeez - I totally overlooked that. Sorry about that. I suspect it's something silly - will look into it. Thanks for the report!

**Comment by dselans** [comment]
@kamalhm I didn't notice this immediately - this just seems like a shell issue. If you quote the input data as `'{"test":"with space"}'` it should work properly.

If it wasn't JSON - you would just do `"some long sentence"` and it would work fine.

**Comment by kamalhm** [comment]
I see, I think we should add this info on the readme

**Comment by dselans** [comment]
Agreed - I updated the README with a note on this. Thanks for pointing out and sorry for not noticing the underlying problem earlier - woops!
