### ISSUE TITLE
not buildable from source

### ISSUE THREAD

**Issue by shibumi** [batchcorp/plumber#208]
**Describe the bug**

Version v1.0.0 is not buildable from source, because one of its dependencies is not public available:

```
go: github.com/batchcorp/inferschema@v0.0.4: reading github.com/batchcorp/inferschema/go.mod at revision v0.0.4: git ls-remote -q origin in /build/go/pkg/mod/cache/vcs/cee0f32bc125cd938ce5343397a3d327fcb90b9d314ebdf991db6d045ed551af: exit status 128:
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

**To Reproduce**
1. Download the software
2. Run `go build -o plumber .`

**Expected behavior**

It should be possible to compile this software from source.

**Comment by blinktag** [comment]
Sorry about that! That functionality isn't ready for primetime yet. Commented out for now so you are able to build

**Comment by shibumi** [comment]
@blinktag is this included in the release v1.0.0? If not: can you draft a new release v1.0.1 with the fix? I would like to package this software for the Arch Linux repositories :)

**Comment by uzarubin** [comment]
> @blinktag is this included in the release v1.0.0? If not: can you draft a new release v1.0.1 with the fix? I would like to package this software for the Arch Linux repositories :)

Please post a link to the aur here. I'm the only arch Linux user at batchcorp 😀

**Comment by shibumi** [comment]
@uzarubin I am not talking about the AUR. I am not talking about the official repositories :)

**Comment by uzarubin** [comment]
> @uzarubin I am not talking about the AUR. I am  talking about the official repositories :)

You are too kind!

**Comment by dselans** [comment]
@shibumi new release posted: https://github.com/batchcorp/plumber/releases/tag/v1.0.1

Thanks for getting us into Arch - really awesome! Ping if you have any other suggestions!

**Comment by shibumi** [comment]
@dselans  THANK YOU :) that was fast

**Comment by shibumi** [comment]
@uzarubin https://archlinux.org/packages/community/x86_64/plumber/

**Comment by dselans** [comment]
> @dselans THANK YOU :) that was fast

Haha, same applies to you! https://archlinux.org/packages/community/x86_64/plumber/

Thank you for getting plumber in there so fast!
