### ISSUE TITLE
CLI Params required for SQS

### ISSUE THREAD

**Issue by phumberdroz** [batchcorp/plumber#218]
**Describe the bug**
Previously plumber would just pick up my AWS_PROFILE env var and authenticate and read from an SQS queue. 
Recently I upgraded and it is no longer working
**To Reproduce**
➜ plumber read aws-sqs --queue-name=<QUEUE_NAME> -f
FATA[0000] Unable to handle CLI input: unable to parse CLI options: missing flags: --aws-access-key-id=STRING, --aws-region=STRING, --aws-secret-access-key=STRING

**Expected behavior**
Messages should be produced 

**Screenshots**

**CLI (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] 1.1.1

**Additional context**

**Comment by dselans** [comment]
Thanks for the report - should be a quick and easy fix. Will update here when done.

**Comment by blinktag** [comment]
Hi @phumberdroz,

Please try https://github.com/batchcorp/plumber/releases/tag/v1.1.2 and let me know if you have any further issues

**Comment by phumberdroz** [comment]
hey 👋 

Works again! thanks a lot! Love the tool!
