### ISSUE TITLE
Improve functional test suite

### ISSUE THREAD

**Issue by dselans** [batchcorp/plumber#26]
Current functional test suite is very hit or miss - very likely needs to be redone altogether.

Would probably leave kafka for last due to slow initialization times (and thus difficult to quickly iterate).

Also need to figure out how we'll test messaging systems that can't be run locally (such as GCP PubSub, SQS, Azure).

EDIT: Now that we have `relay` mode and `plumber` is expected to run without issues long-term - we must have a reliable testing story.

**Comment by blinktag** [comment]
We can try and use the following for testing locally
Azure - https://hub.docker.com/_/microsoft-azure-storage-azurite
GCP - https://github.com/marcelcorso/gcloud-pubsub-emulator
AWS - https://hub.docker.com/r/localstack/localstack

**Comment by blinktag** [comment]
Decided to move these tests to the package level
