### ISSUE TITLE
Nats jetstream arguments 

### ISSUE THREAD

**Issue by edarha** [batchcorp/plumber#289]
Hi guys, when I read messages from nats-jetstream, it hasn't arguments such as `since (start by time), sequence,..` like nats streaming. I think if nats-jetstream has these arguments above will be better. Hopefully, you guys can improve it asap. many thanks guys !!!

**Comment by blinktag** [comment]
Great suggestion @edarha! We will work on getting those added shortly

**Comment by dselans** [comment]
@blinktag is cutting a new release as v1.10.1.

This new release supports consumer usage and has things like StartSequence, StartTime and more.

The docs and examples are updated as well. Thanks for submitting the issue!
