### ISSUE TITLE
Nats-jetstream feature

### ISSUE THREAD

**Issue by edarha** [batchcorp/plumber#303]
Nats jetstream has a way to connect server by [nkey](https://github.com/nats-io/nats.go#new-authentication-nkeys-and-user-credentials), so could you guys help to add this logic if you have time, thanks guys

**Comment by dselans** [comment]
We're looking into it - thanks for the report!

**Comment by blinktag** [comment]
@edarha we have added a new `--nkey` flag to nats/nats-jetstream backends in https://github.com/batchcorp/plumber/releases/tag/v1.11.0
The flag accepts either a path to the file containing the nkey seed, or the seed directly as the argument. Let me know if everything is working for you

**Comment by edarha** [comment]
thanks guys for helping
