### ISSUE TITLE
Improve test coverage for `backends/awssns`

### ISSUE THREAD

**Issue by brainsnail** [batchcorp/plumber#313]
## What are we looking for?
We're looking to improve test coverage across the board. In this case, first start by checking the existing coverage by running `make test/dev` to get a sense of the existing coverage. Then take a look at existing tests to see how to cover the codebase. We'd like to improve coverage as we believe it gives folks higher confidence in the code that they are running. 

For an example PR that includes an update to tests check out https://github.com/batchcorp/plumber/pull/296/files

**Comment by vimalpatel19** [comment]
I'd like to assist and contribute towards this.

**Comment by brainsnail** [comment]
Thanks @vimalpatel19 - just tag me if you open a PR and I'll take a look. We appreciate it!
