### ISSUE TITLE
cannot pipe, due to --input read options

### ISSUE THREAD

**Issue by chris-aeviator** [batchcorp/plumber#331]
**Describe the bug**

**To Reproduce**
create a text file

```
my first message
my second message
```

Pipe the data to plumber as seen in docs

```
cat test-data.txt | plumber write kafka --address kafka:9092 --topics topic
```

**Expected behavior**
plumber writes two messages to kafka

**Actual behavior**
`FATA[0000] unable to complete command: unable to validate read options: either --input or --input-file or  must be specified`

when using `--input-file test-data.txt` only one message is written

**Screenshots**

**CLI (please complete the following information):**
 - OS: arch
 - Version v1.14.3-b53811e

**Additional context**

**Comment by blinktag** [comment]
Thanks for the report @chris-aeviator, we'll get a fix out shortly

**Comment by blinktag** [comment]
@chris-aeviator The issue is fixed now in https://github.com/batchcorp/plumber/releases/tag/v2.0.0
