### ISSUE TITLE
Telemetry error logs

### ISSUE THREAD

**Issue by ShayNehmad-RecoLabs** [batchcorp/plumber#337]
**Describe the bug**

I opted in for telemetry and whenever I run the tool this is the output:

```
posthog 2023/02/23 03:57:36 ERROR: sending request - Post "https://telemetry.streamdal.com/batch/": x509: “localhost” certificate is not standards compliant
posthog 2023/02/23 03:57:36 ERROR: sending request - Post "https://telemetry.streamdal.com/batch/": x509: “localhost” certificate is not standards compliant
posthog 2023/02/23 03:57:37 ERROR: sending request - Post "https://telemetry.streamdal.com/batch/": x509: “localhost” certificate is not standards compliant
posthog 2023/02/23 03:57:38 ERROR: sending request - Post "https://telemetry.streamdal.com/batch/": x509: “localhost” certificate is not standards compliant
posthog 2023/02/23 03:57:39 ERROR: sending request - Post "https://telemetry.streamdal.com/batch/": x509: “localhost” certificate is not standards compliant
```

**To Reproduce**
1. Literally run any plumber command after opting in 

**Expected behavior**
Don't show the error - I don't care about the telemetry

**Screenshots**

**CLI (please complete the following information):**
 - OS: Mac
 - Version 13.2.1 (22D68)

**Additional context**
I'd also like to understand how to opt out in case I want/need to

**Comment by blinktag** [comment]
@ShayNehmad-RecoLabs apologies for the trouble, we should have this fixed shortly

**Comment by blinktag** [comment]
@ShayNehmad-RecoLabs we have resolved the certificate issue. Can you please try now
