### ISSUE TITLE
unknown flag --json-array

### ISSUE THREAD

**Issue by chris-aeviator** [batchcorp/plumber#339]
**Describe the bug**
When trying to use the `--json-array` functionality to pipe data into plumber, the CLI errors with `FATA[0000] Unable to handle CLI input: unable to parse CLI options: unknown flag --json-array`

**To Reproduce**

`echo '[{"foo": "bar"}]' | plumber write kafka --address kafka:9092 --topics myTopic --json-array`

**Expected behavior**
plumber sends a message for each array element.

**CLI (please complete the following information):**
 - OS: arch linux
```
❯ plumber --version
v2.1.0-5355376
```

**Comment by blinktag** [comment]
@chris-aeviator the flag was changed to `--input-as-json-array`. I will get the docs updated this week to correct the flag. Sorry for the confusion!
