### ISSUE TITLE
Azure Service Bus Issues

### ISSUE THREAD

**Issue by azizabah** [batchcorp/plumber#340]
**Describe the bug**
Two bugs:
There is an issue with the Azure Service Bus (ASB) examples. It lists "azure" as the argument but the CLI checks you and asks for "azure-service-bus" or "azure-event-hub". 

There is an issue with the CLI validation for ASB queues. It thinks topic is always required.

**To Reproduce**
plumber write azure-service-bus --queue="name" --input="test"
FATA[0000] Unable to handle CLI input: unable to parse CLI options: missing flags: --topic=STRING 

**Expected behavior**
That it sends the message to the queue.

**Screenshots**

**CLI (please complete the following information):**
 - OS: MacOS
 - Version v2.1.0-5355376

**Comment by blinktag** [comment]
Thank you for the report @azizabah ! we have fixed these issues in https://github.com/batchcorp/plumber/releases/tag/v2.1.1
