### ISSUE TITLE
Read from kafka as consumer group is not working

### ISSUE THREAD

**Issue by alok87** [batchcorp/plumber#50]
## Works
I am trying to read using https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go it works.
```
go run main.go --brokers=$KAFKA --group=inventory-reload-batcher-a1c3de --topics=db.inventory.customers
```
The sarma consumer here does not require one minute or two, it just starts working.

## Does not work
It hangs at trying to initialize the request. I saw the code has an infinite loop and does not log any error so that the user can fix something. 
But when I read using plumber it does not.
```
plumber read kafka --address $KAFKA --topic db.inventory.customers  --group-id inventory-reload-batcher-a1c3de
INFO[0000] Initializing (could take a minute or two) ...  pkg=kafka/read.go
```

Please help out here.

**Comment by dselans** [comment]
I'll need to investigate this a bit more. We use the kafka lib from segment which has all kinds of batching/high-perf support baked into the library - due to this, the initial connect takes some time to spin up. So that _might_ be the problem or there's an actual bug. 

In either case, we'll give this a whirl and keep you updated.

**Comment by blinktag** [comment]
Hi @alok87

We believe the issue should be fixed in https://github.com/batchcorp/plumber/releases/tag/v0.8.1
Can you let us know if you have any troubles with this release. Thank you!

**Comment by dselans** [comment]
Sidenote: turns out it had nothing to do with the perf stuff in segment lib - it was related to us not doing proper connection closing. Woops! @alok87 - issue should be fixed - please test. We'll be closing this issue if we don't hear anything back.

Thanks!

**Comment by dselans** [comment]
We are using these changes internally and have ceased seeing the weird lag - you should see the same. Let us know if that's not the case. Thanks for reporting! Clossing issue.
