### ISSUE TITLE
Unable to start plumber

### ISSUE THREAD

**Issue by Tak1za** [batchcorp/plumber#6]
After following the steps mentioned to download the binary and make it executable, I get the error: ```/usr/local/bin/plumber: 1: Not: not found``` upon running the command: ```plumber -h``` or ```plumber -v```

**Comment by FarzamAlam** [comment]
Just do one thing `ls -al` and see the size of plumber. May be you have not downloaded properly. You can do below mentioned steps then.
1. First of all you have to export VERSION=v0.1.0
2. Then you can run 
	`curl -o plumber https://github.com/batchcorp/plumber/releases/download/$VERSION/plumber-darwin`
3. If you are having problem with curl then you can use
	`wget https://github.com/batchcorp/plumber/releases/download/$VERSION/plumber-darwin`
	`mv plumber-darwin plumber`

**Comment by Tak1za** [comment]
curl was causing the problem.
When I used wget it worked. Thanks!
