### ISSUE TITLE
Support for publishing only to AWS/SNS

### ISSUE THREAD

**Issue by pfortin-urbn** [batchcorp/plumber#60]
It would be nice sometimes to publish to an AWS topic?

**Comment by dselans** [comment]
Makes sense. Should be nice and easy too. We'll make it happen!

**Comment by blinktag** [comment]
@pfortin-urbn. Thanks for the suggestion! SNS support has been added in [v0.11.0](https://github.com/batchcorp/plumber/releases/tag/v0.11.0)

Example usage:

```bash
plumber write aws-sns --topic="arn:aws:sns:us-east-2:123456789012:MyTopic" --input-data="A new is ready for processing!"
```
