### ISSUE TITLE
Installation on macOS causes Apple to issue a warning

### ISSUE THREAD

**Issue by adamhaney** [batchcorp/plumber#7]
When I followed the installation instructions, even though I set the binary to be executable Apple threw their "This binary was downloaded from the internet and isn't signed" warning message and wouldn't allow me to execute it. I had to navigate to the binary in finder and then right click to open it before Apple gave me the option to trust it. Perhaps we need to look into some other signing/packaging solution to make the installation smoother for users?

**Comment by uzarubin** [comment]
We're working on getting this into homebrew core. I'm wondering if that would fix it.

**Comment by dselans** [comment]
It's now possible to install via `brew`. I think it'll take a lot to get the app "approved"/"signed" by apple so for the time being we might just stick an FAQ entry on docs.batch.sh (or in the README).

I think we should just wait to see if this comes up again in the future.
