### ISSUE TITLE
[Windows] --with-line-numbers didnt work

### ISSUE THREAD

**Issue by kamalhm** [batchcorp/plumber#8]
kafka read  --with-line-numbers didnt work with an error of
```
time="2020-08-08T11:07:34+07:00" level=fatal msg="Unable to handle CLI input: unable to parse command: unknown long flag '--with-line-numbers'"
```

command used
`plumber read messages kafka --topic foo --with-line-numbers --follow`

**Comment by dselans** [comment]
Will fix, thanks for filing the issue.

**Comment by dselans** [comment]
Hey there, I think this may have been due to incorrect docs AND it may have been missing in the previous CLI flag implementation. It should be good now. Use `--line-numbers`.
