### ISSUE TITLE
Support for Azure EventHub

### ISSUE THREAD

**Issue by mladedav** [batchcorp/plumber#88]
I believe this should be straightforward as it will be very similar to Service Bus.

I am willing to contribute if this feature is wanted.

**Comment by blinktag** [comment]
@mladedav Azure Event hub support has been added in v0.21.0. You may use the commands `plumber read azure-eventhub -h` and `plumber write azure-eventhub -h` to view available flags. Examples have also been added to https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md#azure-event-hub and https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md#azure-event-hub-1

Let us know if you needed any additional functionality for this
