### ISSUE TITLE
Support for NATS Streaming

### ISSUE THREAD

**Issue by nguyenhoaibao** [batchcorp/plumber#92]
I think this is more or less the same with NATS, but using https://github.com/nats-io/stan.go instead.

**Comment by blinktag** [comment]
@nguyenhoaibao This is definitely be doable! Give us a few days and I'll have a release for you

**Comment by nguyenhoaibao** [comment]
Hi, have we done this yet? If not I'm happy to open a PR to implement this.

**Comment by blinktag** [comment]
@nguyenhoaibao streaming support has been added in v0.21.0. You may use the commands `plumber read nats-streaming -h` and `plumber write nats-streaming -h` to view available flags. Examples have also been added to https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md#nats-streaming and https://github.com/batchcorp/plumber/blob/master/EXAMPLES.md#nats-streaming-1

Let us know if you needed any additional functionality for this

**Comment by nguyenhoaibao** [comment]
It works perfectly, thanks @blinktag. 

BTW I think it will be great if we can support more options like [this](https://github.com/nats-io/stan.go/blob/master/examples/stan-sub/main.go#L40):
```
--last                           Deliver starting with last published message
--since  <time_ago>              Deliver messages in last interval (e.g. 1s, 1hr)
--seq    <seqno>                 Start at seqno
--new_only                       Only deliver new messages
```

**Comment by blinktag** [comment]
@nguyenhoaibao I added `--all` `--since` `--last` and `--seq` in the latest release, and made new-only the default behavior of the read command

**Comment by nguyenhoaibao** [comment]
Great. Thanks for doing this. I'll close this now.
