### ISSUE TITLE
Support for AWS SQS FIFO Queues

### ISSUE THREAD

**Issue by azizabah** [batchcorp/plumber#95]
To write to a FIFO queue in AWS SQS, you must supply a MessageGroupId. It looks like Plumber doesn't currently support this (I could be wrong - I'm definitely new to golang). 

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html 

If you don't supply it, you get rejected with a 400 like this:
```
FATA[0000] Unable to complete command: unable to complete message send: MissingParameter: The request must contain the parameter MessageGroupId.
status code: 400, request id: c667b6b4-42d9-5bb3-be3e-ee5d2e8888ca 
```

**Comment by dselans** [comment]
Thanks for the report! Looks like @blinktag has already pushed a fix - should have a release out later tonight!

**Comment by blinktag** [comment]
@azizabah I have added the `--message-group-id` to fix your issue. Also added the `--message-deduplication-id` in the event that deduplication isn't enabled on the FIFO queue. Let me know if you have any further issues

**Comment by azizabah** [comment]
@blinktag - Just tested and it worked perfectly. Also good call for adding the dedupe, that was a missed requirement on my part. Thanks again for the quick turn around!
